// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/unix-streamdeck/streamdeckd/streamdeckd (interfaces: IApplicationManager,IBackgrounder,IForegrounder,IHandlerPruner,IInputManager,IPageManager,IVirtualDev)
//
// Generated by this command:
//
//	mockgen -package=mocks -destination=mocks/mocks.go . IApplicationManager,IBackgrounder,IForegrounder,IHandlerPruner,IInputManager,IPageManager,IVirtualDev
//

// Package mocks is a generated GoMock package.
package streamdeckd

import (
	image "image"
	log "log"
	reflect "reflect"

	v2 "github.com/unix-streamdeck/api/v2"
	driver "github.com/unix-streamdeck/driver"
	gomock "go.uber.org/mock/gomock"
)

// MockIApplicationManager is a mock of IApplicationManager interface.
type MockIApplicationManager struct {
	ctrl     *gomock.Controller
	recorder *MockIApplicationManagerMockRecorder
	isgomock struct{}
}

// MockIApplicationManagerMockRecorder is the mock recorder for MockIApplicationManager.
type MockIApplicationManagerMockRecorder struct {
	mock *MockIApplicationManager
}

// NewMockIApplicationManager creates a new mock instance.
func NewMockIApplicationManager(ctrl *gomock.Controller) *MockIApplicationManager {
	mock := &MockIApplicationManager{ctrl: ctrl}
	mock.recorder = &MockIApplicationManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIApplicationManager) EXPECT() *MockIApplicationManagerMockRecorder {
	return m.recorder
}

// AttachListener mocks base method.
func (m *MockIApplicationManager) AttachListener(listener func(string)) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AttachListener", listener)
}

// AttachListener indicates an expected call of AttachListener.
func (mr *MockIApplicationManagerMockRecorder) AttachListener(listener any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AttachListener", reflect.TypeOf((*MockIApplicationManager)(nil).AttachListener), listener)
}

// GetApplication mocks base method.
func (m *MockIApplicationManager) GetApplication() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetApplication")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetApplication indicates an expected call of GetApplication.
func (mr *MockIApplicationManagerMockRecorder) GetApplication() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetApplication", reflect.TypeOf((*MockIApplicationManager)(nil).GetApplication))
}

// SetApplication mocks base method.
func (m *MockIApplicationManager) SetApplication(application string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetApplication", application)
}

// SetApplication indicates an expected call of SetApplication.
func (mr *MockIApplicationManagerMockRecorder) SetApplication(application any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetApplication", reflect.TypeOf((*MockIApplicationManager)(nil).SetApplication), application)
}

// MockIBackgrounder is a mock of IBackgrounder interface.
type MockIBackgrounder struct {
	ctrl     *gomock.Controller
	recorder *MockIBackgrounderMockRecorder
	isgomock struct{}
}

// MockIBackgrounderMockRecorder is the mock recorder for MockIBackgrounder.
type MockIBackgrounderMockRecorder struct {
	mock *MockIBackgrounder
}

// NewMockIBackgrounder creates a new mock instance.
func NewMockIBackgrounder(ctrl *gomock.Controller) *MockIBackgrounder {
	mock := &MockIBackgrounder{ctrl: ctrl}
	mock.recorder = &MockIBackgrounderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIBackgrounder) EXPECT() *MockIBackgrounderMockRecorder {
	return m.recorder
}

// AttachPageChangeListener mocks base method.
func (m *MockIBackgrounder) AttachPageChangeListener() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AttachPageChangeListener")
}

// AttachPageChangeListener indicates an expected call of AttachPageChangeListener.
func (mr *MockIBackgrounderMockRecorder) AttachPageChangeListener() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AttachPageChangeListener", reflect.TypeOf((*MockIBackgrounder)(nil).AttachPageChangeListener))
}

// SetIndividualKeyBackground mocks base method.
func (m *MockIBackgrounder) SetIndividualKeyBackground(backgrounder v2.KeyBackgrounder, index int) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetIndividualKeyBackground", backgrounder, index)
}

// SetIndividualKeyBackground indicates an expected call of SetIndividualKeyBackground.
func (mr *MockIBackgrounderMockRecorder) SetIndividualKeyBackground(backgrounder, index any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetIndividualKeyBackground", reflect.TypeOf((*MockIBackgrounder)(nil).SetIndividualKeyBackground), backgrounder, index)
}

// SetIndividualLcdBackground mocks base method.
func (m *MockIBackgrounder) SetIndividualLcdBackground(backgrounder v2.LcdSegmentBackgrounder, index int) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetIndividualLcdBackground", backgrounder, index)
}

// SetIndividualLcdBackground indicates an expected call of SetIndividualLcdBackground.
func (mr *MockIBackgrounderMockRecorder) SetIndividualLcdBackground(backgrounder, index any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetIndividualLcdBackground", reflect.TypeOf((*MockIBackgrounder)(nil).SetIndividualLcdBackground), backgrounder, index)
}

// SetKeyBackground mocks base method.
func (m *MockIBackgrounder) SetKeyBackground(backgrounder v2.KeyGridBackgrounder) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetKeyBackground", backgrounder)
}

// SetKeyBackground indicates an expected call of SetKeyBackground.
func (mr *MockIBackgrounderMockRecorder) SetKeyBackground(backgrounder any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetKeyBackground", reflect.TypeOf((*MockIBackgrounder)(nil).SetKeyBackground), backgrounder)
}

// SetLcdBackground mocks base method.
func (m *MockIBackgrounder) SetLcdBackground(backgrounder v2.LcdBackgrounder) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetLcdBackground", backgrounder)
}

// SetLcdBackground indicates an expected call of SetLcdBackground.
func (mr *MockIBackgrounderMockRecorder) SetLcdBackground(backgrounder any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetLcdBackground", reflect.TypeOf((*MockIBackgrounder)(nil).SetLcdBackground), backgrounder)
}

// MockIForegrounder is a mock of IForegrounder interface.
type MockIForegrounder struct {
	ctrl     *gomock.Controller
	recorder *MockIForegrounderMockRecorder
	isgomock struct{}
}

// MockIForegrounderMockRecorder is the mock recorder for MockIForegrounder.
type MockIForegrounderMockRecorder struct {
	mock *MockIForegrounder
}

// NewMockIForegrounder creates a new mock instance.
func NewMockIForegrounder(ctrl *gomock.Controller) *MockIForegrounder {
	mock := &MockIForegrounder{ctrl: ctrl}
	mock.recorder = &MockIForegrounderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIForegrounder) EXPECT() *MockIForegrounderMockRecorder {
	return m.recorder
}

// AttachAppChangeListener mocks base method.
func (m *MockIForegrounder) AttachAppChangeListener() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AttachAppChangeListener")
}

// AttachAppChangeListener indicates an expected call of AttachAppChangeListener.
func (mr *MockIForegrounderMockRecorder) AttachAppChangeListener() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AttachAppChangeListener", reflect.TypeOf((*MockIForegrounder)(nil).AttachAppChangeListener))
}

// AttachPageChangeListener mocks base method.
func (m *MockIForegrounder) AttachPageChangeListener() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AttachPageChangeListener")
}

// AttachPageChangeListener indicates an expected call of AttachPageChangeListener.
func (mr *MockIForegrounderMockRecorder) AttachPageChangeListener() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AttachPageChangeListener", reflect.TypeOf((*MockIForegrounder)(nil).AttachPageChangeListener))
}

// SetKey mocks base method.
func (m *MockIForegrounder) SetKey(currentKeyConfig *v2.KeyConfigV3, keyIndex, page int, activeApp string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetKey", currentKeyConfig, keyIndex, page, activeApp)
}

// SetKey indicates an expected call of SetKey.
func (mr *MockIForegrounderMockRecorder) SetKey(currentKeyConfig, keyIndex, page, activeApp any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetKey", reflect.TypeOf((*MockIForegrounder)(nil).SetKey), currentKeyConfig, keyIndex, page, activeApp)
}

// SetKnob mocks base method.
func (m *MockIForegrounder) SetKnob(currentKnobConfig *v2.KnobConfigV3, knobIndex, page int, activeApp string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetKnob", currentKnobConfig, knobIndex, page, activeApp)
}

// SetKnob indicates an expected call of SetKnob.
func (mr *MockIForegrounderMockRecorder) SetKnob(currentKnobConfig, knobIndex, page, activeApp any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetKnob", reflect.TypeOf((*MockIForegrounder)(nil).SetKnob), currentKnobConfig, knobIndex, page, activeApp)
}

// MockIHandlerPruner is a mock of IHandlerPruner interface.
type MockIHandlerPruner struct {
	ctrl     *gomock.Controller
	recorder *MockIHandlerPrunerMockRecorder
	isgomock struct{}
}

// MockIHandlerPrunerMockRecorder is the mock recorder for MockIHandlerPruner.
type MockIHandlerPrunerMockRecorder struct {
	mock *MockIHandlerPruner
}

// NewMockIHandlerPruner creates a new mock instance.
func NewMockIHandlerPruner(ctrl *gomock.Controller) *MockIHandlerPruner {
	mock := &MockIHandlerPruner{ctrl: ctrl}
	mock.recorder = &MockIHandlerPrunerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIHandlerPruner) EXPECT() *MockIHandlerPrunerMockRecorder {
	return m.recorder
}

// OnAppSwitch mocks base method.
func (m *MockIHandlerPruner) OnAppSwitch() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "OnAppSwitch")
}

// OnAppSwitch indicates an expected call of OnAppSwitch.
func (mr *MockIHandlerPrunerMockRecorder) OnAppSwitch() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OnAppSwitch", reflect.TypeOf((*MockIHandlerPruner)(nil).OnAppSwitch))
}

// OnPageChange mocks base method.
func (m *MockIHandlerPruner) OnPageChange() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "OnPageChange")
}

// OnPageChange indicates an expected call of OnPageChange.
func (mr *MockIHandlerPrunerMockRecorder) OnPageChange() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OnPageChange", reflect.TypeOf((*MockIHandlerPruner)(nil).OnPageChange))
}

// StopAllHandlers mocks base method.
func (m *MockIHandlerPruner) StopAllHandlers() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "StopAllHandlers")
}

// StopAllHandlers indicates an expected call of StopAllHandlers.
func (mr *MockIHandlerPrunerMockRecorder) StopAllHandlers() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StopAllHandlers", reflect.TypeOf((*MockIHandlerPruner)(nil).StopAllHandlers))
}

// MockIInputManager is a mock of IInputManager interface.
type MockIInputManager struct {
	ctrl     *gomock.Controller
	recorder *MockIInputManagerMockRecorder
	isgomock struct{}
}

// MockIInputManagerMockRecorder is the mock recorder for MockIInputManager.
type MockIInputManagerMockRecorder struct {
	mock *MockIInputManager
}

// NewMockIInputManager creates a new mock instance.
func NewMockIInputManager(ctrl *gomock.Controller) *MockIInputManager {
	mock := &MockIInputManager{ctrl: ctrl}
	mock.recorder = &MockIInputManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIInputManager) EXPECT() *MockIInputManagerMockRecorder {
	return m.recorder
}

// GetKeyState mocks base method.
func (m *MockIInputManager) GetKeyState(index int) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetKeyState", index)
	ret0, _ := ret[0].(bool)
	return ret0
}

// GetKeyState indicates an expected call of GetKeyState.
func (mr *MockIInputManagerMockRecorder) GetKeyState(index any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetKeyState", reflect.TypeOf((*MockIInputManager)(nil).GetKeyState), index)
}

// HandleKeyInput mocks base method.
func (m *MockIInputManager) HandleKeyInput(key *v2.KeyV3, event driver.InputEvent) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "HandleKeyInput", key, event)
}

// HandleKeyInput indicates an expected call of HandleKeyInput.
func (mr *MockIInputManagerMockRecorder) HandleKeyInput(key, event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleKeyInput", reflect.TypeOf((*MockIInputManager)(nil).HandleKeyInput), key, event)
}

// HandleKnobInput mocks base method.
func (m *MockIInputManager) HandleKnobInput(knob *v2.KnobV3, event driver.InputEvent) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "HandleKnobInput", knob, event)
}

// HandleKnobInput indicates an expected call of HandleKnobInput.
func (mr *MockIInputManagerMockRecorder) HandleKnobInput(knob, event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleKnobInput", reflect.TypeOf((*MockIInputManager)(nil).HandleKnobInput), knob, event)
}

// MockIPageManager is a mock of IPageManager interface.
type MockIPageManager struct {
	ctrl     *gomock.Controller
	recorder *MockIPageManagerMockRecorder
	isgomock struct{}
}

// MockIPageManagerMockRecorder is the mock recorder for MockIPageManager.
type MockIPageManagerMockRecorder struct {
	mock *MockIPageManager
}

// NewMockIPageManager creates a new mock instance.
func NewMockIPageManager(ctrl *gomock.Controller) *MockIPageManager {
	mock := &MockIPageManager{ctrl: ctrl}
	mock.recorder = &MockIPageManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIPageManager) EXPECT() *MockIPageManagerMockRecorder {
	return m.recorder
}

// AttachListener mocks base method.
func (m *MockIPageManager) AttachListener(channel func(int, int)) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AttachListener", channel)
}

// AttachListener indicates an expected call of AttachListener.
func (mr *MockIPageManagerMockRecorder) AttachListener(channel any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AttachListener", reflect.TypeOf((*MockIPageManager)(nil).AttachListener), channel)
}

// GetPage mocks base method.
func (m *MockIPageManager) GetPage() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPage")
	ret0, _ := ret[0].(int)
	return ret0
}

// GetPage indicates an expected call of GetPage.
func (mr *MockIPageManagerMockRecorder) GetPage() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPage", reflect.TypeOf((*MockIPageManager)(nil).GetPage))
}

// SetPage mocks base method.
func (m *MockIPageManager) SetPage(page int) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetPage", page)
}

// SetPage indicates an expected call of SetPage.
func (mr *MockIPageManagerMockRecorder) SetPage(page any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetPage", reflect.TypeOf((*MockIPageManager)(nil).SetPage), page)
}

// MockIVirtualDev is a mock of IVirtualDev interface.
type MockIVirtualDev struct {
	ctrl     *gomock.Controller
	recorder *MockIVirtualDevMockRecorder
	isgomock struct{}
}

// MockIVirtualDevMockRecorder is the mock recorder for MockIVirtualDev.
type MockIVirtualDevMockRecorder struct {
	mock *MockIVirtualDev
}

// NewMockIVirtualDev creates a new mock instance.
func NewMockIVirtualDev(ctrl *gomock.Controller) *MockIVirtualDev {
	mock := &MockIVirtualDev{ctrl: ctrl}
	mock.recorder = &MockIVirtualDevMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIVirtualDev) EXPECT() *MockIVirtualDevMockRecorder {
	return m.recorder
}

// Backgrounder mocks base method.
func (m *MockIVirtualDev) Backgrounder() IBackgrounder {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Backgrounder")
	ret0, _ := ret[0].(IBackgrounder)
	return ret0
}

// Backgrounder indicates an expected call of Backgrounder.
func (mr *MockIVirtualDevMockRecorder) Backgrounder() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Backgrounder", reflect.TypeOf((*MockIVirtualDev)(nil).Backgrounder))
}

// Close mocks base method.
func (m *MockIVirtualDev) Close() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Close")
}

// Close indicates an expected call of Close.
func (mr *MockIVirtualDevMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockIVirtualDev)(nil).Close))
}

// Config mocks base method.
func (m *MockIVirtualDev) Config() v2.DeckV3 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Config")
	ret0, _ := ret[0].(v2.DeckV3)
	return ret0
}

// Config indicates an expected call of Config.
func (mr *MockIVirtualDevMockRecorder) Config() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Config", reflect.TypeOf((*MockIVirtualDev)(nil).Config))
}

// Foregrounder mocks base method.
func (m *MockIVirtualDev) Foregrounder() IForegrounder {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Foregrounder")
	ret0, _ := ret[0].(IForegrounder)
	return ret0
}

// Foregrounder indicates an expected call of Foregrounder.
func (mr *MockIVirtualDevMockRecorder) Foregrounder() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Foregrounder", reflect.TypeOf((*MockIVirtualDev)(nil).Foregrounder))
}

// HandleScreenLockChange mocks base method.
func (m *MockIVirtualDev) HandleScreenLockChange(locked bool) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "HandleScreenLockChange", locked)
}

// HandleScreenLockChange indicates an expected call of HandleScreenLockChange.
func (mr *MockIVirtualDevMockRecorder) HandleScreenLockChange(locked any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleScreenLockChange", reflect.TypeOf((*MockIVirtualDev)(nil).HandleScreenLockChange), locked)
}

// HandlerPruner mocks base method.
func (m *MockIVirtualDev) HandlerPruner() IHandlerPruner {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandlerPruner")
	ret0, _ := ret[0].(IHandlerPruner)
	return ret0
}

// HandlerPruner indicates an expected call of HandlerPruner.
func (mr *MockIVirtualDevMockRecorder) HandlerPruner() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandlerPruner", reflect.TypeOf((*MockIVirtualDev)(nil).HandlerPruner))
}

// InputManager mocks base method.
func (m *MockIVirtualDev) InputManager() IInputManager {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InputManager")
	ret0, _ := ret[0].(IInputManager)
	return ret0
}

// InputManager indicates an expected call of InputManager.
func (mr *MockIVirtualDevMockRecorder) InputManager() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InputManager", reflect.TypeOf((*MockIVirtualDev)(nil).InputManager))
}

// IsOpen mocks base method.
func (m *MockIVirtualDev) IsOpen() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsOpen")
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsOpen indicates an expected call of IsOpen.
func (mr *MockIVirtualDevMockRecorder) IsOpen() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsOpen", reflect.TypeOf((*MockIVirtualDev)(nil).IsOpen))
}

// Logger mocks base method.
func (m *MockIVirtualDev) Logger() *log.Logger {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Logger")
	ret0, _ := ret[0].(*log.Logger)
	return ret0
}

// Logger indicates an expected call of Logger.
func (mr *MockIVirtualDevMockRecorder) Logger() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Logger", reflect.TypeOf((*MockIVirtualDev)(nil).Logger))
}

// Open mocks base method.
func (m *MockIVirtualDev) Open(rawDev *driver.Device) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Open", rawDev)
	ret0, _ := ret[0].(error)
	return ret0
}

// Open indicates an expected call of Open.
func (mr *MockIVirtualDevMockRecorder) Open(rawDev any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Open", reflect.TypeOf((*MockIVirtualDev)(nil).Open), rawDev)
}

// PageManager mocks base method.
func (m *MockIVirtualDev) PageManager() IPageManager {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PageManager")
	ret0, _ := ret[0].(IPageManager)
	return ret0
}

// PageManager indicates an expected call of PageManager.
func (mr *MockIVirtualDevMockRecorder) PageManager() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PageManager", reflect.TypeOf((*MockIVirtualDev)(nil).PageManager))
}

// RedrawKey mocks base method.
func (m *MockIVirtualDev) RedrawKey(keyIndex int) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RedrawKey", keyIndex)
}

// RedrawKey indicates an expected call of RedrawKey.
func (mr *MockIVirtualDevMockRecorder) RedrawKey(keyIndex any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RedrawKey", reflect.TypeOf((*MockIVirtualDev)(nil).RedrawKey), keyIndex)
}

// SdInfo mocks base method.
func (m *MockIVirtualDev) SdInfo() *v2.StreamDeckInfoV1 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SdInfo")
	ret0, _ := ret[0].(*v2.StreamDeckInfoV1)
	return ret0
}

// SdInfo indicates an expected call of SdInfo.
func (mr *MockIVirtualDevMockRecorder) SdInfo() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SdInfo", reflect.TypeOf((*MockIVirtualDev)(nil).SdInfo))
}

// Serial mocks base method.
func (m *MockIVirtualDev) Serial() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Serial")
	ret0, _ := ret[0].(string)
	return ret0
}

// Serial indicates an expected call of Serial.
func (mr *MockIVirtualDevMockRecorder) Serial() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Serial", reflect.TypeOf((*MockIVirtualDev)(nil).Serial))
}

// SetBrightness mocks base method.
func (m *MockIVirtualDev) SetBrightness(brightness uint8) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetBrightness", brightness)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetBrightness indicates an expected call of SetBrightness.
func (mr *MockIVirtualDevMockRecorder) SetBrightness(brightness any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetBrightness", reflect.TypeOf((*MockIVirtualDev)(nil).SetBrightness), brightness)
}

// SetConfig mocks base method.
func (m *MockIVirtualDev) SetConfig(v3 v2.DeckV3) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetConfig", v3)
}

// SetConfig indicates an expected call of SetConfig.
func (mr *MockIVirtualDevMockRecorder) SetConfig(v3 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetConfig", reflect.TypeOf((*MockIVirtualDev)(nil).SetConfig), v3)
}

// SetKeyBackground mocks base method.
func (m *MockIVirtualDev) SetKeyBackground(keyIndex, page int) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetKeyBackground", keyIndex, page)
}

// SetKeyBackground indicates an expected call of SetKeyBackground.
func (mr *MockIVirtualDevMockRecorder) SetKeyBackground(keyIndex, page any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetKeyBackground", reflect.TypeOf((*MockIVirtualDev)(nil).SetKeyBackground), keyIndex, page)
}

// SetKeyForeground mocks base method.
func (m *MockIVirtualDev) SetKeyForeground(img image.Image, keyIndex, page int) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetKeyForeground", img, keyIndex, page)
}

// SetKeyForeground indicates an expected call of SetKeyForeground.
func (mr *MockIVirtualDevMockRecorder) SetKeyForeground(img, keyIndex, page any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetKeyForeground", reflect.TypeOf((*MockIVirtualDev)(nil).SetKeyForeground), img, keyIndex, page)
}

// SetPanelBackground mocks base method.
func (m *MockIVirtualDev) SetPanelBackground(knobIndex, page int) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetPanelBackground", knobIndex, page)
}

// SetPanelBackground indicates an expected call of SetPanelBackground.
func (mr *MockIVirtualDevMockRecorder) SetPanelBackground(knobIndex, page any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetPanelBackground", reflect.TypeOf((*MockIVirtualDev)(nil).SetPanelBackground), knobIndex, page)
}

// SetPanelForeground mocks base method.
func (m *MockIVirtualDev) SetPanelForeground(img image.Image, knobIndex, page int) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetPanelForeground", img, knobIndex, page)
}

// SetPanelForeground indicates an expected call of SetPanelForeground.
func (mr *MockIVirtualDevMockRecorder) SetPanelForeground(img, knobIndex, page any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetPanelForeground", reflect.TypeOf((*MockIVirtualDev)(nil).SetPanelForeground), img, knobIndex, page)
}
